spring:
  data:
    mongodb:
      database: notes
      port: 27017
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/sanotes
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /sanotes-openapi

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrigins: '*'
